name: bill_share
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.0.0
  auto_route: ^9.2.0
  auto_route_generator: ^9.0.0
  get_it: ^8.0.2
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_svg: ^2.0.14
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5
  supabase_flutter: ^2.8.0
  google_sign_in: ^6.2.2
  dartz: ^0.10.1
  pinput: ^5.0.0
  lottie: ^3.1.3
  blur: ^4.0.0
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  in_app_purchase: ^3.2.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.9.0


flutter:
  generate: true
  uses-material-design: true

  
  assets:
    - assets/images/png/
    - assets/images/png/android/
    - assets/images/png/ios/
    - assets/lottie/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
